### ISSUE TITLE
入力した数の型変換について

### ISSUE THREAD

**Issue by yajima-c0a21129** [c0a21019f2/ProExD#1]
https://github.com/c0a21019f2/ProExD/blob/ed9f4b57e02ded96541d0616cda1490fdd199fda/ex01/alphabet.py#L36

入力した数が数字ではなく文字だった場合エラーを出してしまうので入力した数ではなく、lenで出した数字をstrに変換すると良くなると思ます。

**Comment by c0a21019f2** [comment]
修正しました。ありがとうございます。
