### ISSUE TITLE
テキストの表示位置に関して

### ISSUE THREAD

**Issue by yajima-c0a21129** [c0a21019f2/ProExD#6]
https://github.com/c0a21019f2/ProExD/blob/0cd5507ac89f8a4eeecff07113d80d68fc8c673a/ex03/maze.py#L66

テキストに表示位置はキャンバスの真ん中であっていますか？
テキストの真ん中に表示したい場合はキャンバスの幅が1500であるので1500//2になると思います。
余計なお世話だと思いますが複数回利用する値は変数などで名前を付けておくと分かりやすくなると思います。

**Comment by c0a21019f2** [comment]
ありがとうございます。修正しました。
