### ISSUE TITLE
何のための変数かわかりません。

### ISSUE THREAD

**Issue by C0A21059** [c0a21019f2/ProExD#8]
https://github.com/c0a21019f2/ProExD/blob/6c2a23595154f75ffcb99ae8cf64041369c9c690/ex04/dodge_bomb.py#L7
これらの変数の説明がないため、何のためにあるのか追記したほうがいいと思います。

**Comment by c0a21019f2** [comment]
説明を追記しました。ご指摘ありがとうございます。
