### ISSUE TITLE
check_bound関数内のreturn以降のコードについて

### ISSUE THREAD

**Issue by yajima-c0a21129** [c0a21019f2/ProExD#9]
https://github.com/c0a21019f2/ProExD/blob/4e71a59078bc0f2694a6709057101b0915a0ce8b/ex04/dodge_bomb.py#L21

1つ前の行のreturnは必ず通るようになっているので、21行目から先は関数を呼び出しても読み込まれないと思います。

**Comment by c0a21019f2** [comment]
だ
